### ISSUE TITLE
wagmi too low version

### ISSUE THREAD

**Issue by chuanyu0201** [privy-io/wagmi-demo#8]
@privy-io/wagmi-connector  The version of the binding is too low and inconvenient to use.   Can I upgrade the wagmi version I rely on?

**Comment by nhaga** [comment]
@ahollenbach  any chance you can open source the wagmi-connector so we can adapt it to wagmi >2 ?

**Comment by ankushswar1** [comment]
Hey all - apologies for the lag here! Privy is now compatible with wagmi v2, you can see the instructions to upgrade [here](https://docs.privy.io/guide/guides/wagmi) or refer to the updated source code of this repo!
